version: '3'
services:
  server:
    container_name: 'server'
    build: .
    volumes:
      - ./:/go/src/back
    ports:
      - "8083:8083"
  mysql:
    container_name: 'mysql5'
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: Attendance-2019
      MYSQL_DATABASE: attendance_db